version: '3'
services:
  nginx:
    image: maplegend/mof-nginx:master
    networks:
      - redis-net
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443

  web:
    image: maplegend/minute-of-fame:master
    command: daphne -b 0.0.0.0 -p 8000 minute_of_fame.asgi:application
    restart: always
    hostname: web
    environment:
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis

  multi_connection:
    image: maplegend/multi_connection:master
    command: node server --port 9001
    restart: always
    networks:
      - redis-net
    ports:
      - 9001:9001

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
