version: '3'
services:
  nginx:
    image: maplegend/mof-nginx:master
    networks:
      - main
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
      - 9001:9001

  web:
    env_file:
      - ./service.env
      - ./web.env
      - ./db.env
      - ./secret.env
    image: rg.nl-ams.scw.cloud/minuteoffame/minute-of-fame:master
    command: /bin/sh -c "python manage.py migrate && python manage.py createcachetable && python manage.py runserver 0.0.0.0:80"
    restart: always
    hostname: web
    environment:
      - RHOST=redis
      - NODE_ENV=production
    networks:
      - main
    depends_on:
      - db

  distributor:
    env_file:
      - ./service.env
      - ./secret.env
    image: rg.nl-ams.scw.cloud/minuteoffame/websocket-distributor:master
    hostname: distributor
    networks:
      - main
    depends_on:
      - web
    ports:
      - 4321:4321

  chat:
    env_file:
      - ./service.env
    image: rg.nl-ams.scw.cloud/minuteoffame/mof-chat:master
    hostname: chat
    networks:
      - main
    depends_on:
      - distributor

  queue:
    env_file:
      - ./service.env
    image: rg.nl-ams.scw.cloud/minuteoffame/mof-queue:master
    hostname: queue
    networks:
      - main
    depends_on:
      - distributor

  poll:
    env_file:
      - ./service.env
    image: rg.nl-ams.scw.cloud/minuteoffame/mof-poll:master
    hostname: chat
    networks:
      - main
    depends_on:
      - distributor

  multi_connection:
    image: maplegend/multi_connection:master
    command: node server --port 9001
    restart: always
    hostname: multi_connection
    networks:
      - main

  db:
    env_file:
      - ./db.env
    image: postgres
    restart: always
    hostname: db
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/


networks:
  main:

volumes:
  redis-data:
