version: '3'
services:
  web:
    env_file:
      - ./web.env
      - ./db.env
    image: maplegend/minute-of-fame:master
    command: daphne -b 0.0.0.0 -p 80 minute_of_fame.asgi:application
    restart: always
    ports:
      - "80:80"
    environment:
      - RHOST=redis
    networks:
      - main
    depends_on:
      - redis

  multi_connection:
    image: maplegend/multi_connection:master
    command: node server --port 9001
    restart: always
    networks:
      - main
    ports:
      - 9001:9001

  db:
    env_file:
      - ./db.env
    image: postgres
    restart: always
    hostname: db
    networks:
      - main
    volumes:
      - ./db_data:/var/lib/postgresql/

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    hostname: redis
    networks:
      - main
    volumes:
      - redis-data:/data

networks:
  main:

volumes:
  redis-data:
